Updating the code for Haystack 2.0-Beta
bogdankostic/notion-haystack pull request #1
Opened 2023-12-06 16:18 UTC by TuanaCelik

2023-12-07 11:52 UTC, bogdankostic requested changes
Nice, thank you Tuana! Also very cool that you added an example notebook. 💙

This is almost good to go, I just have some minor comments mostly related to adding some explanations to the notebook

2023-12-07 11:52 UTC, bogdankostic commented on notion_haystack/notion_exporter.py
> +    def run(self, page_ids: List[str])-> Tuple[Dict, str]:
The output type annotation doesn't apply anymore for Haystack 2.0
```suggestion
    def run(self, page_ids: List[str]):
```

2023-12-07 11:52 UTC, bogdankostic commented on examples/indexing.ipynb
> +    "!pip install nest-asyncio\n",
Maybe we can add a comment here why `nest-asyncio` is needed?

2023-12-07 11:52 UTC, bogdankostic commented on examples/indexing.ipynb
> +    "import os\n",
```suggestion
```
`os` is not used in the example.

2023-12-07 11:52 UTC, bogdankostic commented on examples/indexing.ipynb
> +   "source": [
Maybe we can add a comment here that this is a minimal example to just export pages as Haystack Documents.

2023-12-07 11:52 UTC, bogdankostic commented on examples/indexing.ipynb
> +   "source": [
Maybe we can add a comment here saying that this is a full indexing pipeline that will index the Notion pages directly to the document store.

2023-12-08 13:19 UTC, TuanaCelik commented on examples/indexing.ipynb
> +    "!pip install nest-asyncio\n",
done

2023-12-08 13:19 UTC, TuanaCelik commented on examples/indexing.ipynb
> +   "source": [
done

2023-12-08 14:47 UTC, merged